# Generated by Django 4.1.3 on 2022-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='path',
            field=models.FileField(upload_to='public/uploads/'),
        ),
    ]
