# Generated by Django 4.1.3 on 2022-12-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_createmodel_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createmodel',
            old_name='path',
            new_name='file',
        ),
    ]
