# Generated by Django 4.1.3 on 2022-11-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'db_table': 'comments',
                'index_together': {('created_at', 'updated_at')},
            },
        ),
    ]
