# Generated by Django 4.1.3 on 2022-11-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_categories_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
