# Generated by Django 4.1.3 on 2022-11-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_id_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categories'),
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_id',
        ),
    ]
